### ISSUE TITLE
Links not working in exported PDF

### ISSUE THREAD

**Issue by saswatsamal** [realdennis/md2pdf#36]
I used the simple markdown link format to add a link
```
[write your text](write the link)
```
It worked in the preview format, but when I exported it into a PDF file, all the links vanished, and none of them worked.

**Suggestion**: Printing a PDF file removes the link(s) attached to the PDF file. Rather saving the PDF file preserves the link. So if you put an option for saving rather than printing then I guess all the links will work perfectly as we get in the preview.

**Comment by hacklschorsch** [comment]
Links do work for me when I print to PDF.  Platform: Win 10 / Iridium Version 2020.11  (A data privacy minded browser based on Chromium 85)

**Comment by saswatsamal** [comment]
Google Chrome @hacklschorsch !

**Comment by hacklschorsch** [comment]
Strange. Can you double check the links are not in the resulting PDF?

**Comment by saswatsamal** [comment]
I reinstalled my chrome and tried again, it worked! 🎉
Thank you for the help!
