### ISSUE TITLE
Set sensible file name default

### ISSUE THREAD

**Issue by hacklschorsch** [realdennis/md2pdf#37]
Thank you for this very nice service!

Here's a "nice to have" suggestion:

Use case: I already wrote an .md file in my favorite Editor (nvim) and now want to turn it into a PDF.
I find your service on the internet, use it, but when I transform my document the file name is set to `md2pdf - Markdown to PDF.pdf` because that's (still) the `<title>` of the web app.
It does so every time - it doesn't even remember the name when *Transform* multiple times.

Maybe it's easy to suggest a filename, maybe [like so](https://stackoverflow.com/questions/42014507/how-can-i-set-the-default-filename-for-the-chrome-print-dialog-from-within-an-if).
You could get the filename from the chosen uploaded file, and make that override some other sane default, like choosing the biggest headline title (`# h1 head line badumm tuss!`) as file name.

It would be even nicer if it remembered the file name I chose the last time, but I don't know if that is easy to do.

**Comment by realdennis** [comment]
Interesting, will take a look, maybe wrap a print function with a trick effect (change title) and cleanup later.

**Comment by realdennis** [comment]
@hacklschorsch thanks for this awesome suggestion! the change has been released, take a look on it!

**Comment by hacklschorsch** [comment]
Works for me, thanks!
