### ISSUE TITLE
API availability doesn't exist

### ISSUE THREAD

**Issue by anthonymesa** [realdennis/md2pdf#39]
This is my first time ever creating an issue on someone else's repo, so I apologize if this is bad form.

I would like to use this service in an API related capacity to send markdown content and print options over a POST request that returns the pdf, is this a possible feature or something that I would be able to collaborate on in the future?

**Comment by realdennis** [comment]
Sorry for the late reply, all the logic is in client-side JavaScript, so there is no API.
