### ISSUE TITLE
how can i add images to the markdown files?

### ISSUE THREAD

**Issue by mba1398** [realdennis/md2pdf#46]
while,
thank you for your job.
there a question.
how can i add images to the markdown files?
Look forward to your favourable reply，ths a lot.

**Comment by mba1398** [comment]
a question

**Comment by DavidProf** [comment]
Please do some research before asking this here (I'm not trying to be gross).

Well you can find your answer [here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#images)

Or here:

```Markdown
![Alt text](https://myimage.link/logo.png)
```

If you have a image on your computer so you have two options:
- Publish to a public space and copy the link of the image
- Start a simple server to serve the image use localhost for the link. E.g. `![My local image](http://localhost:3000/logo.png)`
