### ISSUE TITLE
Can't find the offline web app

### ISSUE THREAD

**Issue by ShahriarKh** [realdennis/md2pdf#48]
The readme says there is an offline web app, but I can't find it :(

**Comment by realdennis** [comment]
Now u can try it on https://md2pdf.netlify.app/
<img width="1312" alt="pwa" src="https://user-images.githubusercontent.com/26633162/133892104-a4b50efc-12ad-469b-b9fb-a272961f4f84.png">

**Comment by ShahriarKh** [comment]
Thanks!
Did you change anything? I visited the website before posting an issue but Chrome didn't show the "install" option. I'm asking to see if there was problem with my connection (or maybe I didn't wait enough) or something really changed.
