### ISSUE TITLE
Not support firefox

### ISSUE THREAD

**Issue by yiyu0x** [realdennis/md2pdf#7]
As title, not support firefox (im using firefox 65.0.1)
the function bar was not show.

**Comment by realdennis** [comment]
https://github.com/realdennis/md2pdf/commit/28ae6d657517ecb31ef4e8d47537f5ac229a5fee#diff-b07d2669a1bffb29161014cbf58714f5R34
Fix the style issue, 
but this app seems to work badly in FireFox currently.

**Comment by realdennis** [comment]
https://github.com/realdennis/md2pdf/commit/7dce762e04b929323e8651a1d0e9f2097eebe81f#diff-62413eda7b1a3bf30ef614e8fc2138b0R26

Solved.
Test in v67.0b1 & v65.0.1.
