### ISSUE TITLE
the page was freezing in chromium

### ISSUE THREAD

**Issue by yiyu0x** [realdennis/md2pdf#8]
when i use chromium to choose my MD file, the page was freezing
![freeze](https://i.imgur.com/2DcXh00.png)

**Comment by realdennis** [comment]
It works for me. (Chromium v57)
Could you reproduce this bug?

**Comment by yiyu0x** [comment]
this bug is on Chromium 68 (click "transform" button and print page doesn't work). i just upgrade to Chromium 75, its normal functioning.
![chromium](https://i.imgur.com/cdd5Ood.png)

**Comment by realdennis** [comment]
@yiyu0x Latest version recommended :P
